<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>Sugoi.space &middot; {% block title %}File Hosting{% endblock %}</title>
	<link rel="shortcut icon" href=favicon.ico type="image/x-icon">
	<link rel="stylesheet" href="pomf.min.css">
</head>
<body>
<div class="container">
	{% block body %}What the fuck are you doing here, baka?{% endblock %}
</div>
</body>
</html>
